# Generated by Django 2.1.15 on 2020-03-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20200303_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
